# Generated by Django 4.2.30 on 2026-07-10 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance_app', '0004_documenttype_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current monthly salary (AED) — used on salary/letter documents', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('request', 'Employee Request Letter'), ('hr', 'HR Issued Letter')], max_length=20)),
                ('letter_type', models.CharField(choices=[('salary_hike_request', 'Salary Hike Request Letter'), ('leave_request', 'Leave Request Letter'), ('hike_approval', 'Salary Hike Approval Letter'), ('experience', 'Experience Letter'), ('noc', 'No Objection Certificate (NOC)')], max_length=30)),
                ('reference_no', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='attendance_app.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
