# Generated by Django 4.2.30 on 2026-07-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance_app', '0005_employee_current_salary_generatedletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedletter',
            name='letter_type',
            field=models.CharField(choices=[('salary_hike_request', 'Salary Hike Request Letter'), ('leave_request', 'Leave Request Letter'), ('hike_approval', 'Salary Hike Approval Letter'), ('experience', 'Experience Letter'), ('noc', 'No Objection Certificate (NOC)'), ('warning', 'Warning / Disciplinary Letter')], max_length=30),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Period From')),
                ('to_date', models.DateField(verbose_name='Period To')),
                ('ot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='OT Amount (AED)')),
                ('leave_days', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Total Leave/Absent Days')),
                ('leave_deduction_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Leave Deduction Amount (AED)')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Settlement Amount (AED)')),
                ('settlement_date', models.DateField(default=django.utils.timezone.now, verbose_name='Settlement Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='attendance_app.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
    ]
